### ISSUE TITLE
Doubt on precedence in the constraint

### ISSUE THREAD

**Issue by ElFosco** [CPMpy/cpmpy#210] opened 2023-01-16 17:41 UTC
Writing these lines of code leads to an error

### 
``` python3
from cpmpy import *

model = Model()
test = intvar(0, 1000, name="test")
model += (test <= 100 & test >= 50)
model.solve()
```
I suppose it is due to the fact that it is evaluating 100 & test immediately, in fact if you change with 

``` python3
model += ((test <= 100) & (test >= 50))
```
It works properly

**Comment by JoD** [comment] 2023-01-27 08:54
From 'How to debug':

>   - when using `&` and `|`, make sure to always put the subexpressions in brackets. E.g. `(x == 1) & (y == 0)` instead of `x == 1 & y == 0`. The latter wont work, because Python will unfortunately think you meant `x == (1 & (y == 0))`.

When I try
```
from cpmpy import *

model = Model()
test = intvar(0, 1000, name="test")
model += (test <= 100) & (test >= 50)
print(model.solve())
```
it seems to work.

**Comment by JoD** [comment] 2023-01-27 10:07
It is related to https://github.com/CPMpy/cpmpy/issues/152

I will close this as a duplicate of that one.

**Closed by JoD** 2023-01-27 10:07 UTC
